# Generated by Django 3.1.5 on 2021-02-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_comment_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tittle',
            new_name='price',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
