# Generated by Django 3.2.6 on 2021-10-13 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engine', '0006_auto_20210220_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(default='media/default/user.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
